apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: example-namespace
type: Opaque
data:
  # Replace 'your-secret' with base64 encoded value of your secret
  secret-key: your-secret
